const responseObj = {
    hello:"Hey! How can I help you?",
    Hello:"Hey! How can I help you?",
    hey:"Hey! How can I help you?",
    hai:"Hey! How can I help you?",
    Hey:"Hey! How can I help you?",
    Hai:"Hey! How can I help you?",
    "hi there":"Hey! How can I help you?",
    "Hi":"Hey! How can I help you?",
    hi:"Hey! How can I help you?",
    "hai there":"Hey! How can I help you?",
    today:new Date().toDateString(),
    time:new Date().toLocaleTimeString(),
    "hostel intime":"5.45 pm",
    intime:"5.45 pm",
    "Any canteen nearby":"Fruit stall beside Amaravathi hostel",
    "any canteen nearby":"Fruit stall beside Amaravathi hostel",
    "Any canteen nearby?":"Fruit stall beside Amaravathi hostel",
    "any canteen nearby?":"Fruit stall beside Amaravathi hostel",
    "is there any canteen nearby":"Fruit stall beside Amaravathi hostel",
    canteen:"Fruit stall beside Amaravathi hostel",
    "when general permission is available":"Available for every 2nd and 4th saturday and on any occasion",
    "general permission":"Available for every 2nd and 4th saturday and on any occasion",
    "contact number of amaravathi hostel":"Refer contact page",
    "contact number of kaveri hostel":"Refer contact page",
    "contact number of bhavani hostel":"Refer contact page",
    "contact number for amaravathi hostel":"Refer contact page",
    "contact number for kaveri hostel":"Refer contact page",
    "contact number for bhavani hostel":"Refer contact page",
    "contact number":"Refer contact page",
    "contact":"Refer contact page",
    "can we go outing in weekends":"It is not permitted",
    "can we go outing":"It is not permitted",
    "Can we go outing":"It is not permitted",
    "can we go outing?":"It is not permitted",
    "Can we go outing?":"It is not permitted",
    "can we go for outing?":"It is not permitted",
    "Can we go for outing?":"It is not permitted",
    "can we go for outing during weekends?":"It is not permitted",
    "Can we go for outing during weekends?":"It is not permitted",
    "is there non-veg in the menu":"No ,the mess is pure veg",
    "non-veg":"No ,the mess is pure veg",
    outing:"It is not permitted",
    "how many persons in single room":"Hostels contain two,three and five sitter rooms",
    "how many people in single room":"Hostels contain two,three and five sitter rooms",
    "amaravathi hostel":"Refer Kec Hostel website",
    "kaveri hostel":"Refer Kec Hostel website",
    "bhavani hostel":"Refer Kec Hostel website",
    "amaravathi":"Refer Kec Hostel website",
    "kaveri":"Refer Kec Hostel website",
    "bhavani":"Refer Kec Hostel website",
    "breakfast time":"7.30 am to 8.30 am",
    "lunch time":"12.30 pm to 1.30 pm",
    "dinner time":"7.30 pm to 8.30 pm",
    "biometric time":"7.30 pm to 8.00 pm",
    biometric:"Students presence is checked through biometric every night",
    "breakfast":"7.30 am to 8.30 am",
    "lunch":"12.30 pm to 1.30 pm",
    "dinner":"7.30 pm to 8.30 pm",
    "biometric":"7.30 pm to 8.00 pm",
    "breakfast menu":"Check the website",
    "lunch menu":"Check the website",
    "dinner menu":"Check the website",
    "hostel essentials":"Contact for necessary details",
    "how many hostels are there":"There are 3 hostels:Amaravathi,Kaveri,Bhavani",
    "can we order food":"You can allowed to order food only in food court",
    "can we order food from swiggy":"You can allowed to order food only in food court",
    "can we order food from zomato":"You can allowed to order food only in food court",
    "can we order food from online":"You can allowed to order food only in food court",
    "can we order food online":"You can allowed to order food only in food court",
    "can we order food from online food ordering websites":"You can allowed to order food only in food court",
    "can we order food from any online food ordering websites":"You can allowed to order food only in food court",
    "is there non-veg":"No, the mess is purely veg",
    "is there non veg":"No, the mess is purely veg",
    "is non-veg available in the hostel menu":"No, the mess is purely veg",
    "is non veg available in the hostel menu":"No, the mess is purely veg",
    hostel:"There are 3 hostels:Amaravathi,Kaveri,Bhavani",
    "phone allowed in the hostel premises":"Yes, you are allowed to use your mobile phone inside the room",
    "phone allowed in the hostel":"Yes, you are allowed to use your mobile phone inside the room",
    "Is phone allowed in the hostel premises":"Yes, you are allowed to use your mobile phone inside the room",
    "Is phone allowed inside the hostel premises":"Yes, you are allowed to use your mobile phone inside the room",
    "Is phone allowed in the hostel premises?":"Yes, you are allowed to use your mobile phone inside the room",
    "Is phone allowed inside the hostel premises?":"Yes, you are allowed to use your mobile phone inside the room",
    bye:"Bye!Take Care",
    "Thank You":"Bye!Take Care",
};
